"""Configuration package."""

from .constants import (
    VideoStatus,
    ProjectVideoStatus,
    ProjectStatus,
    SourceType,
    SamplingStrategy,
    FilterModel,
    DetectorType,
    DedupModelType,
    DinoEmbeddingStage,
    StageName,
    VIDEO_INPUT_STATUS,
    VIDEO_IN_PROGRESS_STATUS,
    VIDEO_OUTPUT_STATUS,
    PROJECT_VIDEO_INPUT_STATUS,
    PROJECT_VIDEO_IN_PROGRESS_STATUS,
    PROJECT_VIDEO_OUTPUT_STATUS,
    FILTER_TERMINAL_STATUSES,
    VIDEO_TERMINAL_STATUSES,
    SIGLIP2_MODELS,
    SIGLIP2_DEFAULT,
    DINO_MODELS,
    DINO_DEFAULT,
    YOUTUBE_DOMAINS,
    YOUTUBE_BASE_URL,
)
from .config import (
    DownloadConfig,
    ExtractionConfig,
    FilterConfig,
    DeduplicationConfig,
    DetectionConfig,
    DatabaseConfig,
    LoggingConfig,
    SupervisorConfig,
    MonitorConfig,
    BackupConfig,
)
from .loader import (
    load_config,
    get_database_config,
    get_download_config,
    get_extraction_config,
    get_filter_config,
    get_deduplication_config,
    get_detection_config,
    get_logging_config,
    get_supervisor_config,
    get_monitor_config,
    get_backup_config,
    get_project_name,
    get_output_dir,
    reload_config,
    init_hf_auth,
)

__all__ = [
    # Constants
    "VideoStatus",
    "ProjectVideoStatus",
    "ProjectStatus",
    "SourceType",
    "SamplingStrategy",
    "FilterModel",
    "DetectorType",
    "DedupModelType",
    "DinoEmbeddingStage",
    "StageName",
    "VIDEO_INPUT_STATUS",
    "VIDEO_OUTPUT_STATUS",
    "PROJECT_VIDEO_INPUT_STATUS",
    "PROJECT_VIDEO_OUTPUT_STATUS",
    "SIGLIP2_MODELS",
    "SIGLIP2_DEFAULT",
    "DINO_MODELS",
    "DINO_DEFAULT",
    "YOUTUBE_DOMAINS",
    "YOUTUBE_BASE_URL",
    # Config classes
    "DownloadConfig",
    "ExtractionConfig",
    "FilterConfig",
    "DeduplicationConfig",
    "DetectionConfig",
    "DatabaseConfig",
    "LoggingConfig",
    "SupervisorConfig",
    # Config loaders
    "get_database_config",
    "get_download_config",
    "get_extraction_config",
    "get_filter_config",
    "get_deduplication_config",
    "get_detection_config",
    "get_logging_config",
    "get_supervisor_config",
    "get_project_name",
    "get_output_dir",
    "reload_config",
    "init_hf_auth",
]

